openapi: 3.0.3
info:
  title: OpenAPI schema for template terraform-aws-elasticache-redis
components:
  schemas:
    variables:
      type: object
      required:
      - infrastructure
      properties:
        context:
          title: Context
          type: object
          description: |
            Receive contextual information. When Walrus deploys, Walrus will inject specific contextual information into this field.
          default: {}
          nullable: true
          additionalProperties:
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Advanced
            hidden: true
            order: 1
        infrastructure:
          title: Infrastructure
          type: object
          description: |
            Specify the infrastructure information for deploying.
          required:
          - vpc_id
          properties:
            domain_suffix:
              description: |
                Specify the domain suffix of the CloudMap. The domain suffix must be a valid DNS name.
              nullable: true
              title: Domain Suffix
              type: string
              x-walrus-ui:
                order: 3
            kms_key_id:
              description: |
                Specify the KMS key ID which to encrypt the Redis data. If not specified, the Redis data will not be encrypted.
              nullable: true
              title: Kms Key Id
              type: string
              x-walrus-ui:
                order: 2
            vpc_id:
              description: "Specify the VPC ID where the Redis service applies. \n"
              title: Vpc Id
              type: string
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            group: Advanced
            order: 2
        architecture:
          title: Architecture
          type: string
          description: |
            Specify the deployment architecture, select from standalone or replication.
          default: standalone
          enum:
          - standalone
          - replication
          nullable: true
          x-walrus-ui:
            group: Basic
            order: 3
        replication_readonly_replicas:
          title: Replication Readonly Replicas
          type: number
          description: |
            Specify the number of read-only replicas under the replication deployment.
          default: 1
          enum:
          - 1
          - 3
          - 5
          nullable: true
          x-walrus-ui:
            group: Basic
            order: 4
            showIf: architecture=replication
        engine_version:
          title: Engine Version
          type: string
          description: |
            Specify the deployment engine version.
          default: "7.0"
          enum:
          - "7.0"
          - "6.0"
          nullable: true
          x-walrus-ui:
            group: Basic
            order: 5
        engine_parameters:
          title: Engine Parameters
          type: array
          description: |
            Specify the deployment parameters, see https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/ParameterGroups.Redis.html.
          default: []
          items:
            properties:
              name:
                title: Name
                type: string
                x-walrus-ui:
                  order: 1
              value:
                title: Value
                type: string
                x-walrus-ui:
                  order: 2
            required:
            - name
            - value
            type: object
            x-walrus-ui:
              colSpan: 12
          nullable: true
          x-walrus-ui:
            colSpan: 12
            group: Basic
            hidden: true
            order: 6
        password:
          title: Password
          type: string
          description: |
            Specify the account password. If not specified, it will generate a random password. The password must be 16-32 characters long and start with any letter, number, or the following symbols: ! # $ % ^ & * ( ) _ + - =.
            If not specified, it will generate a random password.
          format: password
          nullable: true
          writeOnly: true
          minLength: 16
          maxLength: 32
          x-walrus-ui:
            group: Basic
            order: 7
        resources:
          title: Resources
          type: object
          description: |
            Specify the computing resources.
          default:
            class: cache.t3.micro
          nullable: true
          properties:
            class:
              default: cache.t3.micro
              description: |
                Specify the computing resources. See https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/CacheNodes.SupportedTypes.html.
              nullable: true
              title: Class
              type: string
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 8
      x-walrus-ui:
        groupOrder:
        - Basic
        - Advanced
